String[] data_story = {
  "  call  unpack", 
  "01:00", 
  "  hint {", 
  "    l_grid", 
  "    l_black", 
  "  }", 
  "  copper {", 
  "    l_black    64", 
  "    l_tile    128", 
  "    l_black    256", 
  "  }", 
  "05:00", 
  "  call  blank", 
  "  call  unpack", 
  "06:00", 
  "  copper {", 
  "    l_black    16", 
  "    l_tile    112", 
  "    l_tile_yflip  112", 
  "    l_black    16", 
  "  }", 
  "  main  m_quilt", 
  "18:17", 
  "  call  blank", 
  "  call  unpack", 
  "19:00", 
  "  hint {", 
  "    l_black", 
  "    l_thinsine", 
  "  }", 
  "  copper {", 
  "    l_thinsine  64", 
  "    l_tile    128", 
  "    l_thinsine  256", 
  "  }", 
  "1f:0c", 
  "  vblank  v_grow0", 
  "20:06", 
  "  copper {", 
  "    l_black    2", 
  "    l_thinsine  256", 
  "  }", 
  "21:00", 
  "  copper {", 
  "    l_grid    2", 
  "    l_black    256", 
  "  }", 
  "  main  m_balls", 
  "28:0c", 
  "  hint {", 
  "    l_black", 
  "    l_flash", 
  "    l_twobit", 
  "  }", 
  "  copper {", 
  "    l_twobit  4", 
  "    l_grid    256", 
  "  }", 
  "30:0f", 
  "  vblank  v_nop", 
  "  copper {", 
  "    l_flash    86", 
  "    l_twobit  170", 
  "  }", 
  "30:12", 
  "  copper {", 
  "    l_black    86", 
  "    l_flash    86", 
  "    l_twobit  84", 
  "  }", 
  "30:15", 
  "  copper {", 
  "    l_black    172", 
  "    l_flash    256", 
  "  }", 
  "31:00", 
  "  call  blank", 
  "  copper {", 
  "    l_vu    256", 
  "    l_vu    2", 
  "    l_white    2", 
  "    l_tile    128", 
  "    l_white    2", 
  "    l_vu    256", 
  "  }", 
  "  call  unpack", 
  "32:0c", 
  "  vblank  v_enterpic", 
  "37:0c", 
  "  vblank  v_exitpic", 
  "39:00", 
  "  call  unpack", 
  "  vblank  v_enterpic", 
  "3f:00", 
  "  vblank  v_exitpic", 
  "40:0b", 
  "  hint {", 
  "    l_plasma", 
  "    l_rotozoom", 
  "    l_rle", 
  "    l_column", 
  "  }", 
  "  copper {", 
  "    l_column  4", 
  "    l_vu    256", 
  "  }", 
  "  vblank  v_grow0", 
  "  call  unpack", 
  "44:00", 
  "  vblank  v_nop", 
  "  copper {", 
  "    l_column  256", 
  "    l_column  2", 
  "    l_black    4", 
  "    l_tile    128", 
  "    l_black    4", 
  "    l_column  256", 
  "  }", 
  "  main  m_greets", 
  "  vblank  v_enterpic", 
  "4e:06", 
  "  vblank  v_exitpic", 
  "4f:0c", 
  "  main  m_cube", 
  "4f:13", 
  "  vblank  v_grow0", 
  "  copper {", 
  "    l_rle    2", 
  "    l_column  256", 
  "  }", 
  "50:0f", 
  "  call  addspoke", 
  "50:12", 
  "  call  addspoke", 
  "50:15", 
  "  call  addspoke", 
  "51:03", 
  "  vblank  v_movecube", 
  "5f:06", 
  "  vblank  v_nop", 
  "60:06", 
  "  vblank  v_grow0", 
  "  copper {", 
  "    l_rotozoom  4", 
  "    l_rle    256", 
  "  }", 
  "62:00", 
  "  main  v_nop", 
  "  call  unpack", 
  "  copper {", 
  "    l_rotozoom  256", 
  "    l_rotozoom  2", 
  "    l_white    2", 
  "    l_tile    128", 
  "    l_white    2", 
  "    l_rotozoom  256", 
  "  }", 
  "63:00", 
  "  vblank  v_enterpic", 
  "67:0a", 
  "  vblank  v_exitpic", 
  "68:0a", 
  "  call  initplasma", 
  "  copper {", 
  "    l_plasma  2", 
  "    l_rotozoom  256", 
  "  }", 
  "  vblank  v_grow0", 
  "70:17", 
  "  call  blank", 
  "  main  m_labyrinth", 
  "71:00", 
  "  copper {", 
  "    l_labyrinth  256", 
  "  }", 
  "84:00", 
  "  call  blank", 
  "  copper {", 
  "    l_flash    256", 
  "  }", 
  "  call  unpack", 
  "84:08", 
  "  copper {", 
  "    l_black    64", 
  "    l_tile    128", 
  "    l_black    256", 
  "  }", 
  "84:0b", 
  "  call  blank", 
  "  call  unpack", 
  "  copper {", 
  "    l_black    64", 
  "    l_tile    128", 
  "    l_black    256", 
  "  }", 
  "87:00", 
  "  call  blank", 
  "88:00"
};